#!/usr/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; tab-width 4; indent-width 4; replace-tabs on; eol unix;

import socket
import argparse


host      = "127.0.0.1"
localhost = "127.0.0.1"
port      = 1344

parser = argparse.ArgumentParser(description='Parameters for icap_client:')

parser.add_argument('--file', '-f', dest='file_path', type=str, required=True,
                    help='set file to scan path')

args = parser.parse_args()


file_path = args.file_path
file_path_list = file_path.split("/")
filename  = file_path_list[len(file_path_list)-1]
f = open(file_path, "r")
content = f.read(128)

socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.connect((host, port))
print "Connection on {}".format(host+":"+str(port))

body_req = "POST "+filename+" HTTP/1.1\r\nHost: "+localhost+"\r\n"+"Accept: text/html, text/plain\r\nAccept-Encoding: compress\r\nPragma: no-cache\r\n\r\n"+content

request = "REQMOD icap://"+host+":"+str(port)+"/avscan ICAP/1.0\r\n" +"Host: "+host+":"+str(port)+"\r\n"+"Connection: close\r\n"+"Encapsulated: req-hdr=0, req-body="+str(len(body_req))+"\r\n\r\n"+body_req


socket.send(request.encode("utf-8"))


msg_recu = b""

while msg_recu == b"":

    msg_recu = socket.recv(1024)
    
    if msg_recu != b"":
        print("rcv:")
        print("\""+msg_recu.decode("utf-8")+"\"")
        break

print "Close"
socket.close()


