autogen/configs/autogen/variables_configuration.hpp: \
$(wildcard variant/configs/variant/*.hpp) \
$(wildcard include/configs/*.hpp) \
../utils/config_spec.hpp \
../main/write_cpp_config.cpp \
../utils/apps/app_write_cpp_config.hpp
	./generate_file.sh
