enum authid_t {
    AUTHID_UNKNOWN = 0,
    AUTHID_ACCEPT_MESSAGE,
#define STRAUTHID_ACCEPT_MESSAGE "accept_message"
    AUTHID_ALTERNATE_SHELL,
#define STRAUTHID_ALTERNATE_SHELL "alternate_shell"
    AUTHID_AUTHENTICATED,
#define STRAUTHID_AUTHENTICATED "authenticated"
    AUTHID_AUTHENTICATION_CHALLENGE,
#define STRAUTHID_AUTHENTICATION_CHALLENGE "authentication_challenge"
    AUTHID_AUTH_CHANNEL_ANSWER,
#define STRAUTHID_AUTH_CHANNEL_ANSWER "auth_channel_answer"
    AUTHID_AUTH_CHANNEL_RESULT,
#define STRAUTHID_AUTH_CHANNEL_RESULT "auth_channel_result"
    AUTHID_AUTH_CHANNEL_TARGET,
#define STRAUTHID_AUTH_CHANNEL_TARGET "auth_channel_target"
    AUTHID_AUTH_ERROR_MESSAGE,
#define STRAUTHID_AUTH_ERROR_MESSAGE "auth_error_message"
    AUTHID_AUTH_USER,
#define STRAUTHID_AUTH_USER "login"
    AUTHID_COMMENT,
#define STRAUTHID_COMMENT "comment"
    AUTHID_DISABLE_CLIPBOARD_LOG,
#define STRAUTHID_DISABLE_CLIPBOARD_LOG "disable_clipboard_log"
    AUTHID_DISABLE_KEYBOARD_LOG,
#define STRAUTHID_DISABLE_KEYBOARD_LOG "disable_keyboard_log"
    AUTHID_DISABLE_TSK_SWITCH_SHORTCUTS,
#define STRAUTHID_DISABLE_TSK_SWITCH_SHORTCUTS "disable_tsk_switch_shortcuts"
    AUTHID_DISPLAY_MESSAGE,
#define STRAUTHID_DISPLAY_MESSAGE "display_message"
    AUTHID_DURATION,
#define STRAUTHID_DURATION "duration"
    AUTHID_END_DATE_CNX,
#define STRAUTHID_END_DATE_CNX "timeclose"
    AUTHID_END_TIME,
#define STRAUTHID_END_TIME "end_time"
    AUTHID_FORCEMODULE,
#define STRAUTHID_FORCEMODULE "forcemodule"
    AUTHID_FORMFLAG,
#define STRAUTHID_FORMFLAG "formflag"
    AUTHID_HOST,
#define STRAUTHID_HOST "ip_client"
    AUTHID_KEEPALIVE,
#define STRAUTHID_KEEPALIVE "keepalive"
    AUTHID_KEYBOARD_LAYOUT,
#define STRAUTHID_KEYBOARD_LAYOUT "keyboard_layout"
    AUTHID_LANGUAGE,
#define STRAUTHID_LANGUAGE "language"
    AUTHID_MESSAGE,
#define STRAUTHID_MESSAGE "message"
    AUTHID_MODE_CONSOLE,
#define STRAUTHID_MODE_CONSOLE "mode_console"
    AUTHID_MODULE,
#define STRAUTHID_MODULE "module"
    AUTHID_OPT_BITRATE,
#define STRAUTHID_OPT_BITRATE "bitrate"
    AUTHID_OPT_BPP,
#define STRAUTHID_OPT_BPP "bpp"
    AUTHID_OPT_CLIENT_DEVICE_ANNOUNCE_TIMEOUT,
#define STRAUTHID_OPT_CLIENT_DEVICE_ANNOUNCE_TIMEOUT "client_device_announce_timeout"
    AUTHID_OPT_FILE_ENCRYPTION,
#define STRAUTHID_OPT_FILE_ENCRYPTION "file_encryption"
    AUTHID_OPT_FRAMERATE,
#define STRAUTHID_OPT_FRAMERATE "framerate"
    AUTHID_OPT_HEIGHT,
#define STRAUTHID_OPT_HEIGHT "height"
    AUTHID_OPT_MOVIE,
#define STRAUTHID_OPT_MOVIE "is_rec"
    AUTHID_OPT_MOVIE_PATH,
#define STRAUTHID_OPT_MOVIE_PATH "rec_patch"
    AUTHID_OPT_PROXY_MANAGED_DRIVES,
#define STRAUTHID_OPT_PROXY_MANAGED_DRIVES "proxy_managed_drives"
    AUTHID_OPT_QSCALE,
#define STRAUTHID_OPT_QSCALE "qscale"
    AUTHID_OPT_WABAGENT,
#define STRAUTHID_OPT_WABAGENT "wab_agent"
    AUTHID_OPT_WABAGENT_KEEPALIVE_TIMEOUT,
#define STRAUTHID_OPT_WABAGENT_KEEPALIVE_TIMEOUT "wab_agent_keepalive_timeout"
    AUTHID_OPT_WABAGENT_LAUNCH_TIMEOUT,
#define STRAUTHID_OPT_WABAGENT_LAUNCH_TIMEOUT "wab_agent_launch_timeout"
    AUTHID_OPT_WIDTH,
#define STRAUTHID_OPT_WIDTH "width"
    AUTHID_PASSWORD,
#define STRAUTHID_PASSWORD "password"
    AUTHID_PATTERN_KILL,
#define STRAUTHID_PATTERN_KILL "pattern_kill"
    AUTHID_PATTERN_NOTIFY,
#define STRAUTHID_PATTERN_NOTIFY "pattern_notify"
    AUTHID_PROXY_OPT,
#define STRAUTHID_PROXY_OPT "proxy_opt"
    AUTHID_RDP_BOGUS_SC_NET_SIZE,
#define STRAUTHID_RDP_BOGUS_SC_NET_SIZE "rdp_bogus_sc_net_size"
    AUTHID_REAL_TARGET_DEVICE,
#define STRAUTHID_REAL_TARGET_DEVICE "real_target_device"
    AUTHID_REJECTED,
#define STRAUTHID_REJECTED "rejected"
    AUTHID_REPORTING,
#define STRAUTHID_REPORTING "reporting"
    AUTHID_RT_DISPLAY,
#define STRAUTHID_RT_DISPLAY "rt_display"
    AUTHID_SELECTOR,
#define STRAUTHID_SELECTOR "selector"
    AUTHID_SELECTOR_CURRENT_PAGE,
#define STRAUTHID_SELECTOR_CURRENT_PAGE "selector_current_page"
    AUTHID_SELECTOR_DEVICE_FILTER,
#define STRAUTHID_SELECTOR_DEVICE_FILTER "selector_device_filter"
    AUTHID_SELECTOR_GROUP_FILTER,
#define STRAUTHID_SELECTOR_GROUP_FILTER "selector_group_filter"
    AUTHID_SELECTOR_LINES_PER_PAGE,
#define STRAUTHID_SELECTOR_LINES_PER_PAGE "selector_lines_per_page"
    AUTHID_SELECTOR_NUMBER_OF_PAGES,
#define STRAUTHID_SELECTOR_NUMBER_OF_PAGES "selector_number_of_pages"
    AUTHID_SELECTOR_PROTO_FILTER,
#define STRAUTHID_SELECTOR_PROTO_FILTER "selector_proto_filter"
    AUTHID_SESSION_ID,
#define STRAUTHID_SESSION_ID "session_id"
    AUTHID_SHELL_WORKING_DIRECTORY,
#define STRAUTHID_SHELL_WORKING_DIRECTORY "shell_working_directory"
    AUTHID_SHOWFORM,
#define STRAUTHID_SHOWFORM "showform"
    AUTHID_TARGET,
#define STRAUTHID_TARGET "ip_target"
    AUTHID_TARGET_APPLICATION,
#define STRAUTHID_TARGET_APPLICATION "target_application"
    AUTHID_TARGET_APPLICATION_ACCOUNT,
#define STRAUTHID_TARGET_APPLICATION_ACCOUNT "target_application_account"
    AUTHID_TARGET_APPLICATION_PASSWORD,
#define STRAUTHID_TARGET_APPLICATION_PASSWORD "target_application_password"
    AUTHID_TARGET_DEVICE,
#define STRAUTHID_TARGET_DEVICE "target_device"
    AUTHID_TARGET_HOST,
#define STRAUTHID_TARGET_HOST "target_host"
    AUTHID_TARGET_PASSWORD,
#define STRAUTHID_TARGET_PASSWORD "target_password"
    AUTHID_TARGET_PORT,
#define STRAUTHID_TARGET_PORT "target_port"
    AUTHID_TARGET_PROTOCOL,
#define STRAUTHID_TARGET_PROTOCOL "proto_dest"
    AUTHID_TARGET_USER,
#define STRAUTHID_TARGET_USER "target_login"
    AUTHID_TICKET,
#define STRAUTHID_TICKET "ticket"
    AUTHID_TIMEZONE,
#define STRAUTHID_TIMEZONE "timezone"
    AUTHID_VNC_BOGUS_CLIPBOARD_INFINITE_LOOP,
#define STRAUTHID_VNC_BOGUS_CLIPBOARD_INFINITE_LOOP "vnc_bogus_clipboard_infinite_loop"
    AUTHID_VNC_CLIPBOARD_DOWN,
#define STRAUTHID_VNC_CLIPBOARD_DOWN "clipboard_down"
    AUTHID_VNC_CLIPBOARD_UP,
#define STRAUTHID_VNC_CLIPBOARD_UP "clipboard_up"
    AUTHID_VNC_SERVER_CLIPBOARD_ENCODING_TYPE,
#define STRAUTHID_VNC_SERVER_CLIPBOARD_ENCODING_TYPE "vnc_server_clipboard_encoding_type"
    AUTHID_WAITINFORETURN,
#define STRAUTHID_WAITINFORETURN "waitinforeturn"
    MAX_AUTHID
};
constexpr char const * const authstr[] = {
    STRAUTHID_ACCEPT_MESSAGE, // AUTHID_ACCEPT_MESSAGE
    STRAUTHID_ALTERNATE_SHELL, // AUTHID_ALTERNATE_SHELL
    STRAUTHID_AUTHENTICATED, // AUTHID_AUTHENTICATED
    STRAUTHID_AUTHENTICATION_CHALLENGE, // AUTHID_AUTHENTICATION_CHALLENGE
    STRAUTHID_AUTH_CHANNEL_ANSWER, // AUTHID_AUTH_CHANNEL_ANSWER
    STRAUTHID_AUTH_CHANNEL_RESULT, // AUTHID_AUTH_CHANNEL_RESULT
    STRAUTHID_AUTH_CHANNEL_TARGET, // AUTHID_AUTH_CHANNEL_TARGET
    STRAUTHID_AUTH_ERROR_MESSAGE, // AUTHID_AUTH_ERROR_MESSAGE
    STRAUTHID_AUTH_USER, // AUTHID_AUTH_USER
    STRAUTHID_COMMENT, // AUTHID_COMMENT
    STRAUTHID_DISABLE_CLIPBOARD_LOG, // AUTHID_DISABLE_CLIPBOARD_LOG
    STRAUTHID_DISABLE_KEYBOARD_LOG, // AUTHID_DISABLE_KEYBOARD_LOG
    STRAUTHID_DISABLE_TSK_SWITCH_SHORTCUTS, // AUTHID_DISABLE_TSK_SWITCH_SHORTCUTS
    STRAUTHID_DISPLAY_MESSAGE, // AUTHID_DISPLAY_MESSAGE
    STRAUTHID_DURATION, // AUTHID_DURATION
    STRAUTHID_END_DATE_CNX, // AUTHID_END_DATE_CNX
    STRAUTHID_END_TIME, // AUTHID_END_TIME
    STRAUTHID_FORCEMODULE, // AUTHID_FORCEMODULE
    STRAUTHID_FORMFLAG, // AUTHID_FORMFLAG
    STRAUTHID_HOST, // AUTHID_HOST
    STRAUTHID_KEEPALIVE, // AUTHID_KEEPALIVE
    STRAUTHID_KEYBOARD_LAYOUT, // AUTHID_KEYBOARD_LAYOUT
    STRAUTHID_LANGUAGE, // AUTHID_LANGUAGE
    STRAUTHID_MESSAGE, // AUTHID_MESSAGE
    STRAUTHID_MODE_CONSOLE, // AUTHID_MODE_CONSOLE
    STRAUTHID_MODULE, // AUTHID_MODULE
    STRAUTHID_OPT_BITRATE, // AUTHID_OPT_BITRATE
    STRAUTHID_OPT_BPP, // AUTHID_OPT_BPP
    STRAUTHID_OPT_CLIENT_DEVICE_ANNOUNCE_TIMEOUT, // AUTHID_OPT_CLIENT_DEVICE_ANNOUNCE_TIMEOUT
    STRAUTHID_OPT_FILE_ENCRYPTION, // AUTHID_OPT_FILE_ENCRYPTION
    STRAUTHID_OPT_FRAMERATE, // AUTHID_OPT_FRAMERATE
    STRAUTHID_OPT_HEIGHT, // AUTHID_OPT_HEIGHT
    STRAUTHID_OPT_MOVIE, // AUTHID_OPT_MOVIE
    STRAUTHID_OPT_MOVIE_PATH, // AUTHID_OPT_MOVIE_PATH
    STRAUTHID_OPT_PROXY_MANAGED_DRIVES, // AUTHID_OPT_PROXY_MANAGED_DRIVES
    STRAUTHID_OPT_QSCALE, // AUTHID_OPT_QSCALE
    STRAUTHID_OPT_WABAGENT, // AUTHID_OPT_WABAGENT
    STRAUTHID_OPT_WABAGENT_KEEPALIVE_TIMEOUT, // AUTHID_OPT_WABAGENT_KEEPALIVE_TIMEOUT
    STRAUTHID_OPT_WABAGENT_LAUNCH_TIMEOUT, // AUTHID_OPT_WABAGENT_LAUNCH_TIMEOUT
    STRAUTHID_OPT_WIDTH, // AUTHID_OPT_WIDTH
    STRAUTHID_PASSWORD, // AUTHID_PASSWORD
    STRAUTHID_PATTERN_KILL, // AUTHID_PATTERN_KILL
    STRAUTHID_PATTERN_NOTIFY, // AUTHID_PATTERN_NOTIFY
    STRAUTHID_PROXY_OPT, // AUTHID_PROXY_OPT
    STRAUTHID_RDP_BOGUS_SC_NET_SIZE, // AUTHID_RDP_BOGUS_SC_NET_SIZE
    STRAUTHID_REAL_TARGET_DEVICE, // AUTHID_REAL_TARGET_DEVICE
    STRAUTHID_REJECTED, // AUTHID_REJECTED
    STRAUTHID_REPORTING, // AUTHID_REPORTING
    STRAUTHID_RT_DISPLAY, // AUTHID_RT_DISPLAY
    STRAUTHID_SELECTOR, // AUTHID_SELECTOR
    STRAUTHID_SELECTOR_CURRENT_PAGE, // AUTHID_SELECTOR_CURRENT_PAGE
    STRAUTHID_SELECTOR_DEVICE_FILTER, // AUTHID_SELECTOR_DEVICE_FILTER
    STRAUTHID_SELECTOR_GROUP_FILTER, // AUTHID_SELECTOR_GROUP_FILTER
    STRAUTHID_SELECTOR_LINES_PER_PAGE, // AUTHID_SELECTOR_LINES_PER_PAGE
    STRAUTHID_SELECTOR_NUMBER_OF_PAGES, // AUTHID_SELECTOR_NUMBER_OF_PAGES
    STRAUTHID_SELECTOR_PROTO_FILTER, // AUTHID_SELECTOR_PROTO_FILTER
    STRAUTHID_SESSION_ID, // AUTHID_SESSION_ID
    STRAUTHID_SHELL_WORKING_DIRECTORY, // AUTHID_SHELL_WORKING_DIRECTORY
    STRAUTHID_SHOWFORM, // AUTHID_SHOWFORM
    STRAUTHID_TARGET, // AUTHID_TARGET
    STRAUTHID_TARGET_APPLICATION, // AUTHID_TARGET_APPLICATION
    STRAUTHID_TARGET_APPLICATION_ACCOUNT, // AUTHID_TARGET_APPLICATION_ACCOUNT
    STRAUTHID_TARGET_APPLICATION_PASSWORD, // AUTHID_TARGET_APPLICATION_PASSWORD
    STRAUTHID_TARGET_DEVICE, // AUTHID_TARGET_DEVICE
    STRAUTHID_TARGET_HOST, // AUTHID_TARGET_HOST
    STRAUTHID_TARGET_PASSWORD, // AUTHID_TARGET_PASSWORD
    STRAUTHID_TARGET_PORT, // AUTHID_TARGET_PORT
    STRAUTHID_TARGET_PROTOCOL, // AUTHID_TARGET_PROTOCOL
    STRAUTHID_TARGET_USER, // AUTHID_TARGET_USER
    STRAUTHID_TICKET, // AUTHID_TICKET
    STRAUTHID_TIMEZONE, // AUTHID_TIMEZONE
    STRAUTHID_VNC_BOGUS_CLIPBOARD_INFINITE_LOOP, // AUTHID_VNC_BOGUS_CLIPBOARD_INFINITE_LOOP
    STRAUTHID_VNC_CLIPBOARD_DOWN, // AUTHID_VNC_CLIPBOARD_DOWN
    STRAUTHID_VNC_CLIPBOARD_UP, // AUTHID_VNC_CLIPBOARD_UP
    STRAUTHID_VNC_SERVER_CLIPBOARD_ENCODING_TYPE, // AUTHID_VNC_SERVER_CLIPBOARD_ENCODING_TYPE
    STRAUTHID_WAITINFORETURN, // AUTHID_WAITINFORETURN
};

