/*
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

   Product name: redemption, a FLOSS RDP proxy
   Copyright (C) Wallix 2010
   Author(s): Christophe Grosjean, Javier Caverni
   Based on xrdp Copyright (C) Jay Sorg 2004-2010

   Keymap reader file. keymap object contains all informations
   about keymap read from keymap.ini file

*/

#include "keymap.hpp"
#include "log.hpp"

#include <stdio.h>
#include <stdlib.h>

#include <boost/program_options.hpp>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/tokenizer.hpp>
#include <boost/token_functions.hpp>
#include <iostream>
#include <fstream>
#include <sstream>
#include <map>
#include <string>
#include <string.h>


using namespace std;
namespace po = boost::program_options;

id_keymap keymap_type_from_string(string str)
{
    id_keymap res = ID_UNKNOWN;
    if ((0 == string("noshift").compare(str))
        || (0 == string("NOSHIFT").compare(str))){
            res = ID_NOSHIFT;
    }
    else if ((0 == string("shift").compare(str))
        || (0 == string("SHIFT").compare(str))){
            res = ID_SHIFT;
    }
    else if ((0 == string("altgr").compare(str))
        || (0 == string("ALTGR").compare(str))){
            res = ID_ALTGR;
    }
    else if ((0 == string("capslock").compare(str))
        || (0 == string("CAPSLOCK").compare(str))){
            res = ID_CAPSLOCK;
    }
    else if ((0 == string("shiftcapslock").compare(str))
        || (0 == string("SHIFTCAPSLOCK").compare(str))){
            res = ID_SHIFTCAPSLOCK;
    }
    return res;
}


bool keymap_check_name(string str)
{
    return ((str.length() > 0) && (str.length() < 250));
}

Keymap::Keymap(const char * filename) {
    ifstream  Keymap_stream(filename);
    this->keymap_init(Keymap_stream);
}


Keymap::Keymap(istream & Keymap_stream){
    this->keymap_init(Keymap_stream);
}

/* map for rdp to x11 scancodes code1 is regular scancode, code2 is extended scancode */

void Keymap::keymap_init(istream & Keymap_stream){
#warning find a more generic way to read this struct
    po::options_description Keymap_desc("Keymap_file.ini configuration file:");
    Keymap_desc.add_options()
    ("noshift.Key8", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key9", po::value<string>()->default_value("65307:27"), "")
    ("noshift.Key10", po::value<string>()->default_value("49:49"), "")
    ("noshift.Key11", po::value<string>()->default_value("50:50"), "")
    ("noshift.Key12", po::value<string>()->default_value("51:51"), "")
    ("noshift.Key13", po::value<string>()->default_value("52:52"), "")
    ("noshift.Key14", po::value<string>()->default_value("53:53"), "")
    ("noshift.Key15", po::value<string>()->default_value("54:54"), "")
    ("noshift.Key16", po::value<string>()->default_value("55:55"), "")
    ("noshift.Key17", po::value<string>()->default_value("56:56"), "")
    ("noshift.Key18", po::value<string>()->default_value("57:57"), "")
    ("noshift.Key19", po::value<string>()->default_value("48:48"), "")
    ("noshift.Key20", po::value<string>()->default_value("223:223"), "")
    ("noshift.Key21", po::value<string>()->default_value("65105:180"), "")
    ("noshift.Key22", po::value<string>()->default_value("65288:8"), "")
    ("noshift.Key23", po::value<string>()->default_value("65289:9"), "")
    ("noshift.Key24", po::value<string>()->default_value("113:113"), "")
    ("noshift.Key25", po::value<string>()->default_value("119:119"), "")
    ("noshift.Key26", po::value<string>()->default_value("101:101"), "")
    ("noshift.Key27", po::value<string>()->default_value("114:114"), "")
    ("noshift.Key28", po::value<string>()->default_value("116:116"), "")
    ("noshift.Key29", po::value<string>()->default_value("122:122"), "")
    ("noshift.Key30", po::value<string>()->default_value("117:117"), "")
    ("noshift.Key31", po::value<string>()->default_value("105:105"), "")
    ("noshift.Key32", po::value<string>()->default_value("111:111"), "")
    ("noshift.Key33", po::value<string>()->default_value("112:112"), "")
    ("noshift.Key34", po::value<string>()->default_value("252:252"), "")
    ("noshift.Key35", po::value<string>()->default_value("43:43"), "")
    ("noshift.Key36", po::value<string>()->default_value("65293:13"), "")
    ("noshift.Key37", po::value<string>()->default_value("65507:0"), "")
    ("noshift.Key38", po::value<string>()->default_value("97:97"), "")
    ("noshift.Key39", po::value<string>()->default_value("115:115"), "")
    ("noshift.Key40", po::value<string>()->default_value("100:100"), "")
    ("noshift.Key41", po::value<string>()->default_value("102:102"), "")
    ("noshift.Key42", po::value<string>()->default_value("103:103"), "")
    ("noshift.Key43", po::value<string>()->default_value("104:104"), "")
    ("noshift.Key44", po::value<string>()->default_value("106:106"), "")
    ("noshift.Key45", po::value<string>()->default_value("107:107"), "")
    ("noshift.Key46", po::value<string>()->default_value("108:108"), "")
    ("noshift.Key47", po::value<string>()->default_value("246:246"), "")
    ("noshift.Key48", po::value<string>()->default_value("228:228"), "")
    ("noshift.Key49", po::value<string>()->default_value("65106:94"), "")
    ("noshift.Key50", po::value<string>()->default_value("65505:0"), "")
    ("noshift.Key51", po::value<string>()->default_value("35:35"), "")
    ("noshift.Key52", po::value<string>()->default_value("121:121"), "")
    ("noshift.Key53", po::value<string>()->default_value("120:120"), "")
    ("noshift.Key54", po::value<string>()->default_value("99:99"), "")
    ("noshift.Key55", po::value<string>()->default_value("118:118"), "")
    ("noshift.Key56", po::value<string>()->default_value("98:98"), "")
    ("noshift.Key57", po::value<string>()->default_value("110:110"), "")
    ("noshift.Key58", po::value<string>()->default_value("109:109"), "")
    ("noshift.Key59", po::value<string>()->default_value("44:44"), "")
    ("noshift.Key60", po::value<string>()->default_value("46:46"), "")
    ("noshift.Key61", po::value<string>()->default_value("45:45"), "")
    ("noshift.Key62", po::value<string>()->default_value("65506:0"), "")
    ("noshift.Key63", po::value<string>()->default_value("65450:42"), "")
    ("noshift.Key64", po::value<string>()->default_value("65513:0"), "")
    ("noshift.Key65", po::value<string>()->default_value("32:32"), "")
    ("noshift.Key66", po::value<string>()->default_value("65509:0"), "")
    ("noshift.Key67", po::value<string>()->default_value("65470:0"), "")
    ("noshift.Key68", po::value<string>()->default_value("65471:0"), "")
    ("noshift.Key69", po::value<string>()->default_value("65472:0"), "")
    ("noshift.Key70", po::value<string>()->default_value("65473:0"), "")
    ("noshift.Key71", po::value<string>()->default_value("65474:0"), "")
    ("noshift.Key72", po::value<string>()->default_value("65475:0"), "")
    ("noshift.Key73", po::value<string>()->default_value("65476:0"), "")
    ("noshift.Key74", po::value<string>()->default_value("65477:0"), "")
    ("noshift.Key75", po::value<string>()->default_value("65478:0"), "")
    ("noshift.Key76", po::value<string>()->default_value("65479:0"), "")
    ("noshift.Key77", po::value<string>()->default_value("65407:0"), "")
    ("noshift.Key78", po::value<string>()->default_value("65300:0"), "")
    ("noshift.Key79", po::value<string>()->default_value("65429:0"), "")
    ("noshift.Key80", po::value<string>()->default_value("65431:0"), "")
    ("noshift.Key81", po::value<string>()->default_value("65434:0"), "")
    ("noshift.Key82", po::value<string>()->default_value("65453:45"), "")
    ("noshift.Key83", po::value<string>()->default_value("65430:0"), "")
    ("noshift.Key84", po::value<string>()->default_value("65437:0"), "")
    ("noshift.Key85", po::value<string>()->default_value("65432:0"), "")
    ("noshift.Key86", po::value<string>()->default_value("65451:43"), "")
    ("noshift.Key87", po::value<string>()->default_value("65436:0"), "")
    ("noshift.Key88", po::value<string>()->default_value("65433:0"), "")
    ("noshift.Key89", po::value<string>()->default_value("65435:0"), "")
    ("noshift.Key90", po::value<string>()->default_value("65438:0"), "")
    ("noshift.Key91", po::value<string>()->default_value("65439:0"), "")
    ("noshift.Key92", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key93", po::value<string>()->default_value("65406:0"), "")
    ("noshift.Key94", po::value<string>()->default_value("60:60"), "")
    ("noshift.Key95", po::value<string>()->default_value("65480:0"), "")
    ("noshift.Key96", po::value<string>()->default_value("65481:0"), "")
    ("noshift.Key97", po::value<string>()->default_value("65360:0"), "")
    ("noshift.Key98", po::value<string>()->default_value("65362:0"), "")
    ("noshift.Key99", po::value<string>()->default_value("65365:0"), "")
    ("noshift.Key100", po::value<string>()->default_value("65361:0"), "")
    ("noshift.Key101", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key102", po::value<string>()->default_value("65363:0"), "")
    ("noshift.Key103", po::value<string>()->default_value("65367:0"), "")
    ("noshift.Key104", po::value<string>()->default_value("65364:0"), "")
    ("noshift.Key105", po::value<string>()->default_value("65366:0"), "")
    ("noshift.Key106", po::value<string>()->default_value("65379:0"), "")
    ("noshift.Key107", po::value<string>()->default_value("65535:127"), "")
    ("noshift.Key108", po::value<string>()->default_value("65421:13"), "")
    ("noshift.Key109", po::value<string>()->default_value("65508:0"), "")
    ("noshift.Key110", po::value<string>()->default_value("65299:0"), "")
    ("noshift.Key111", po::value<string>()->default_value("65377:0"), "")
    ("noshift.Key112", po::value<string>()->default_value("65455:47"), "")
    ("noshift.Key113", po::value<string>()->default_value("65027:0"), "")
    ("noshift.Key114", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key115", po::value<string>()->default_value("65515:0"), "")
    ("noshift.Key116", po::value<string>()->default_value("65516:0"), "")
    ("noshift.Key117", po::value<string>()->default_value("65383:0"), "")
    ("noshift.Key118", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key119", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key120", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key121", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key122", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key123", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key124", po::value<string>()->default_value("65027:0"), "")
    ("noshift.Key125", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key126", po::value<string>()->default_value("65469:61"), "")
    ("noshift.Key127", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key128", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key129", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key130", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key131", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key132", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key133", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key134", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key135", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key136", po::value<string>()->default_value("0:0"), "")
    ("noshift.Key137", po::value<string>()->default_value("0:0"), "")


    ("shift.Key8", po::value<string>()->default_value("0:0"), "")
    ("shift.Key9", po::value<string>()->default_value("65307:27"), "")
    ("shift.Key10", po::value<string>()->default_value("33:33"), "")
    ("shift.Key11", po::value<string>()->default_value("34:34"), "")
    ("shift.Key12", po::value<string>()->default_value("167:167"), "")
    ("shift.Key13", po::value<string>()->default_value("36:36"), "")
    ("shift.Key14", po::value<string>()->default_value("37:37"), "")
    ("shift.Key15", po::value<string>()->default_value("38:38"), "")
    ("shift.Key16", po::value<string>()->default_value("47:47"), "")
    ("shift.Key17", po::value<string>()->default_value("40:40"), "")
    ("shift.Key18", po::value<string>()->default_value("41:41"), "")
    ("shift.Key19", po::value<string>()->default_value("61:61"), "")
    ("shift.Key20", po::value<string>()->default_value("63:63"), "")
    ("shift.Key21", po::value<string>()->default_value("65104:96"), "")
    ("shift.Key22", po::value<string>()->default_value("65288:8"), "")
    ("shift.Key23", po::value<string>()->default_value("65056:0"), "")
    ("shift.Key24", po::value<string>()->default_value("81:81"), "")
    ("shift.Key25", po::value<string>()->default_value("87:87"), "")
    ("shift.Key26", po::value<string>()->default_value("69:69"), "")
    ("shift.Key27", po::value<string>()->default_value("82:82"), "")
    ("shift.Key28", po::value<string>()->default_value("84:84"), "")
    ("shift.Key29", po::value<string>()->default_value("90:90"), "")
    ("shift.Key30", po::value<string>()->default_value("85:85"), "")
    ("shift.Key31", po::value<string>()->default_value("73:73"), "")
    ("shift.Key32", po::value<string>()->default_value("79:79"), "")
    ("shift.Key33", po::value<string>()->default_value("80:80"), "")
    ("shift.Key34", po::value<string>()->default_value("220:220"), "")
    ("shift.Key35", po::value<string>()->default_value("42:42"), "")
    ("shift.Key36", po::value<string>()->default_value("65293:13"), "")
    ("shift.Key37", po::value<string>()->default_value("65507:0"), "")
    ("shift.Key38", po::value<string>()->default_value("65:65"), "")
    ("shift.Key39", po::value<string>()->default_value("83:83"), "")
    ("shift.Key40", po::value<string>()->default_value("68:68"), "")
    ("shift.Key41", po::value<string>()->default_value("70:70"), "")
    ("shift.Key42", po::value<string>()->default_value("71:71"), "")
    ("shift.Key43", po::value<string>()->default_value("72:72"), "")
    ("shift.Key44", po::value<string>()->default_value("74:74"), "")
    ("shift.Key45", po::value<string>()->default_value("75:75"), "")
    ("shift.Key46", po::value<string>()->default_value("76:76"), "")
    ("shift.Key47", po::value<string>()->default_value("214:214"), "")
    ("shift.Key48", po::value<string>()->default_value("196:196"), "")
    ("shift.Key49", po::value<string>()->default_value("176:176"), "")
    ("shift.Key50", po::value<string>()->default_value("65505:0"), "")
    ("shift.Key51", po::value<string>()->default_value("39:39"), "")
    ("shift.Key52", po::value<string>()->default_value("89:89"), "")
    ("shift.Key53", po::value<string>()->default_value("88:88"), "")
    ("shift.Key54", po::value<string>()->default_value("67:67"), "")
    ("shift.Key55", po::value<string>()->default_value("86:86"), "")
    ("shift.Key56", po::value<string>()->default_value("66:66"), "")
    ("shift.Key57", po::value<string>()->default_value("78:78"), "")
    ("shift.Key58", po::value<string>()->default_value("77:77"), "")
    ("shift.Key59", po::value<string>()->default_value("59:59"), "")
    ("shift.Key60", po::value<string>()->default_value("58:58"), "")
    ("shift.Key61", po::value<string>()->default_value("95:95"), "")
    ("shift.Key62", po::value<string>()->default_value("65506:0"), "")
    ("shift.Key63", po::value<string>()->default_value("65450:42"), "")
    ("shift.Key64", po::value<string>()->default_value("65511:0"), "")
    ("shift.Key65", po::value<string>()->default_value("32:32"), "")
    ("shift.Key66", po::value<string>()->default_value("65509:0"), "")
    ("shift.Key67", po::value<string>()->default_value("65470:0"), "")
    ("shift.Key68", po::value<string>()->default_value("65471:0"), "")
    ("shift.Key69", po::value<string>()->default_value("65472:0"), "")
    ("shift.Key70", po::value<string>()->default_value("65473:0"), "")
    ("shift.Key71", po::value<string>()->default_value("65474:0"), "")
    ("shift.Key72", po::value<string>()->default_value("65475:0"), "")
    ("shift.Key73", po::value<string>()->default_value("65476:0"), "")
    ("shift.Key74", po::value<string>()->default_value("65477:0"), "")
    ("shift.Key75", po::value<string>()->default_value("65478:0"), "")
    ("shift.Key76", po::value<string>()->default_value("65479:0"), "")
    ("shift.Key77", po::value<string>()->default_value("65273:0"), "")
    ("shift.Key78", po::value<string>()->default_value("65300:0"), "")
    ("shift.Key79", po::value<string>()->default_value("65463:55"), "")
    ("shift.Key80", po::value<string>()->default_value("65464:56"), "")
    ("shift.Key81", po::value<string>()->default_value("65465:57"), "")
    ("shift.Key82", po::value<string>()->default_value("65453:45"), "")
    ("shift.Key83", po::value<string>()->default_value("65460:52"), "")
    ("shift.Key84", po::value<string>()->default_value("65461:53"), "")
    ("shift.Key85", po::value<string>()->default_value("65462:54"), "")
    ("shift.Key86", po::value<string>()->default_value("65451:43"), "")
    ("shift.Key87", po::value<string>()->default_value("65457:49"), "")
    ("shift.Key88", po::value<string>()->default_value("65458:50"), "")
    ("shift.Key89", po::value<string>()->default_value("65459:51"), "")
    ("shift.Key90", po::value<string>()->default_value("65456:48"), "")
    ("shift.Key91", po::value<string>()->default_value("65452:44"), "")
    ("shift.Key92", po::value<string>()->default_value("0:0"), "")
    ("shift.Key93", po::value<string>()->default_value("65406:0"), "")
    ("shift.Key94", po::value<string>()->default_value("62:62"), "")
    ("shift.Key95", po::value<string>()->default_value("65480:0"), "")
    ("shift.Key96", po::value<string>()->default_value("65481:0"), "")
    ("shift.Key97", po::value<string>()->default_value("65360:0"), "")
    ("shift.Key98", po::value<string>()->default_value("65362:0"), "")
    ("shift.Key99", po::value<string>()->default_value("65365:0"), "")
    ("shift.Key100", po::value<string>()->default_value("65361:0"), "")
    ("shift.Key101", po::value<string>()->default_value("0:0"), "")
    ("shift.Key102", po::value<string>()->default_value("65363:0"), "")
    ("shift.Key103", po::value<string>()->default_value("65367:0"), "")
    ("shift.Key104", po::value<string>()->default_value("65364:0"), "")
    ("shift.Key105", po::value<string>()->default_value("65366:0"), "")
    ("shift.Key106", po::value<string>()->default_value("65379:0"), "")
    ("shift.Key107", po::value<string>()->default_value("65535:127"), "")
    ("shift.Key108", po::value<string>()->default_value("65421:13"), "")
    ("shift.Key109", po::value<string>()->default_value("65508:0"), "")
    ("shift.Key110", po::value<string>()->default_value("65299:0"), "")
    ("shift.Key111", po::value<string>()->default_value("65377:0"), "")
    ("shift.Key112", po::value<string>()->default_value("65455:47"), "")
    ("shift.Key113", po::value<string>()->default_value("65027:0"), "")
    ("shift.Key114", po::value<string>()->default_value("0:0"), "")
    ("shift.Key115", po::value<string>()->default_value("65515:0"), "")
    ("shift.Key116", po::value<string>()->default_value("65516:0"), "")
    ("shift.Key117", po::value<string>()->default_value("65383:0"), "")
    ("shift.Key118", po::value<string>()->default_value("0:0"), "")
    ("shift.Key119", po::value<string>()->default_value("0:0"), "")
    ("shift.Key120", po::value<string>()->default_value("0:0"), "")
    ("shift.Key121", po::value<string>()->default_value("0:0"), "")
    ("shift.Key122", po::value<string>()->default_value("0:0"), "")
    ("shift.Key123", po::value<string>()->default_value("0:0"), "")
    ("shift.Key124", po::value<string>()->default_value("65027:0"), "")
    ("shift.Key125", po::value<string>()->default_value("65513:0"), "")
    ("shift.Key126", po::value<string>()->default_value("65469:61"), "")
    ("shift.Key127", po::value<string>()->default_value("65515:0"), "")
    ("shift.Key128", po::value<string>()->default_value("65517:0"), "")
    ("shift.Key129", po::value<string>()->default_value("0:0"), "")
    ("shift.Key130", po::value<string>()->default_value("0:0"), "")
    ("shift.Key131", po::value<string>()->default_value("0:0"), "")
    ("shift.Key132", po::value<string>()->default_value("0:0"), "")
    ("shift.Key133", po::value<string>()->default_value("0:0"), "")
    ("shift.Key134", po::value<string>()->default_value("0:0"), "")
    ("shift.Key135", po::value<string>()->default_value("0:0"), "")
    ("shift.Key136", po::value<string>()->default_value("0:0"), "")
    ("shift.Key137", po::value<string>()->default_value("0:0"), "")

    ("altgr.Key8", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key9", po::value<string>()->default_value("65307:27"), "")
    ("altgr.Key10", po::value<string>()->default_value("185:185"), "")
    ("altgr.Key11", po::value<string>()->default_value("178:178"), "")
    ("altgr.Key12", po::value<string>()->default_value("179:179"), "")
    ("altgr.Key13", po::value<string>()->default_value("188:188"), "")
    ("altgr.Key14", po::value<string>()->default_value("189:189"), "")
    ("altgr.Key15", po::value<string>()->default_value("172:172"), "")
    ("altgr.Key16", po::value<string>()->default_value("123:123"), "")
    ("altgr.Key17", po::value<string>()->default_value("91:91"), "")
    ("altgr.Key18", po::value<string>()->default_value("93:93"), "")
    ("altgr.Key19", po::value<string>()->default_value("125:125"), "")
    ("altgr.Key20", po::value<string>()->default_value("92:92"), "")
    ("altgr.Key21", po::value<string>()->default_value("65115:184"), "")
    ("altgr.Key22", po::value<string>()->default_value("65288:8"), "")
    ("altgr.Key23", po::value<string>()->default_value("65289:9"), "")
    ("altgr.Key24", po::value<string>()->default_value("64:64"), "")
    ("altgr.Key25", po::value<string>()->default_value("435:322"), "")
    ("altgr.Key26", po::value<string>()->default_value("8364:8364"), "")
    ("altgr.Key27", po::value<string>()->default_value("182:182"), "")
    ("altgr.Key28", po::value<string>()->default_value("956:359"), "")
    ("altgr.Key29", po::value<string>()->default_value("2299:8592"), "")
    ("altgr.Key30", po::value<string>()->default_value("2302:8595"), "")
    ("altgr.Key31", po::value<string>()->default_value("2301:8594"), "")
    ("altgr.Key32", po::value<string>()->default_value("248:248"), "")
    ("altgr.Key33", po::value<string>()->default_value("254:254"), "")
    ("altgr.Key34", po::value<string>()->default_value("65111:168"), "")
    ("altgr.Key35", po::value<string>()->default_value("65107:126"), "")
    ("altgr.Key36", po::value<string>()->default_value("65293:13"), "")
    ("altgr.Key37", po::value<string>()->default_value("65507:0"), "")
    ("altgr.Key38", po::value<string>()->default_value("230:230"), "")
    ("altgr.Key39", po::value<string>()->default_value("223:223"), "")
    ("altgr.Key40", po::value<string>()->default_value("240:240"), "")
    ("altgr.Key41", po::value<string>()->default_value("496:273"), "")
    ("altgr.Key42", po::value<string>()->default_value("959:331"), "")
    ("altgr.Key43", po::value<string>()->default_value("689:295"), "")
    ("altgr.Key44", po::value<string>()->default_value("106:106"), "")
    ("altgr.Key45", po::value<string>()->default_value("930:312"), "")
    ("altgr.Key46", po::value<string>()->default_value("435:322"), "")
    ("altgr.Key47", po::value<string>()->default_value("65113:733"), "")
    ("altgr.Key48", po::value<string>()->default_value("65106:94"), "")
    ("altgr.Key49", po::value<string>()->default_value("172:172"), "")
    ("altgr.Key50", po::value<string>()->default_value("65505:0"), "")
    ("altgr.Key51", po::value<string>()->default_value("65104:96"), "")
    ("altgr.Key52", po::value<string>()->default_value("171:171"), "")
    ("altgr.Key53", po::value<string>()->default_value("187:187"), "")
    ("altgr.Key54", po::value<string>()->default_value("162:162"), "")
    ("altgr.Key55", po::value<string>()->default_value("2770:8220"), "")
    ("altgr.Key56", po::value<string>()->default_value("2771:8221"), "")
    ("altgr.Key57", po::value<string>()->default_value("110:110"), "")
    ("altgr.Key58", po::value<string>()->default_value("181:181"), "")
    ("altgr.Key59", po::value<string>()->default_value("2211:0"), "")
    ("altgr.Key60", po::value<string>()->default_value("183:183"), "")
    ("altgr.Key61", po::value<string>()->default_value("65120:0"), "")
    ("altgr.Key62", po::value<string>()->default_value("65506:0"), "")
    ("altgr.Key63", po::value<string>()->default_value("65450:42"), "")
    ("altgr.Key64", po::value<string>()->default_value("65513:0"), "")
    ("altgr.Key65", po::value<string>()->default_value("32:32"), "")
    ("altgr.Key66", po::value<string>()->default_value("65509:0"), "")
    ("altgr.Key67", po::value<string>()->default_value("65470:0"), "")
    ("altgr.Key68", po::value<string>()->default_value("65471:0"), "")
    ("altgr.Key69", po::value<string>()->default_value("65472:0"), "")
    ("altgr.Key70", po::value<string>()->default_value("65473:0"), "")
    ("altgr.Key71", po::value<string>()->default_value("65474:0"), "")
    ("altgr.Key72", po::value<string>()->default_value("65475:0"), "")
    ("altgr.Key73", po::value<string>()->default_value("65476:0"), "")
    ("altgr.Key74", po::value<string>()->default_value("65477:0"), "")
    ("altgr.Key75", po::value<string>()->default_value("65478:0"), "")
    ("altgr.Key76", po::value<string>()->default_value("65479:0"), "")
    ("altgr.Key77", po::value<string>()->default_value("65407:0"), "")
    ("altgr.Key78", po::value<string>()->default_value("65300:0"), "")
    ("altgr.Key79", po::value<string>()->default_value("65429:0"), "")
    ("altgr.Key80", po::value<string>()->default_value("65431:0"), "")
    ("altgr.Key81", po::value<string>()->default_value("65434:0"), "")
    ("altgr.Key82", po::value<string>()->default_value("65453:45"), "")
    ("altgr.Key83", po::value<string>()->default_value("65430:0"), "")
    ("altgr.Key84", po::value<string>()->default_value("65437:0"), "")
    ("altgr.Key85", po::value<string>()->default_value("65432:0"), "")
    ("altgr.Key86", po::value<string>()->default_value("65451:43"), "")
    ("altgr.Key87", po::value<string>()->default_value("65436:0"), "")
    ("altgr.Key88", po::value<string>()->default_value("65433:0"), "")
    ("altgr.Key89", po::value<string>()->default_value("65435:0"), "")
    ("altgr.Key90", po::value<string>()->default_value("65438:0"), "")
    ("altgr.Key91", po::value<string>()->default_value("65439:0"), "")
    ("altgr.Key92", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key93", po::value<string>()->default_value("65406:0"), "")
    ("altgr.Key94", po::value<string>()->default_value("124:124"), "")
    ("altgr.Key95", po::value<string>()->default_value("65480:0"), "")
    ("altgr.Key96", po::value<string>()->default_value("65481:0"), "")
    ("altgr.Key97", po::value<string>()->default_value("65360:0"), "")
    ("altgr.Key98", po::value<string>()->default_value("65362:0"), "")
    ("altgr.Key99", po::value<string>()->default_value("65365:0"), "")
    ("altgr.Key100", po::value<string>()->default_value("65361:0"), "")
    ("altgr.Key101", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key102", po::value<string>()->default_value("65363:0"), "")
    ("altgr.Key103", po::value<string>()->default_value("65367:0"), "")
    ("altgr.Key104", po::value<string>()->default_value("65364:0"), "")
    ("altgr.Key105", po::value<string>()->default_value("65366:0"), "")
    ("altgr.Key106", po::value<string>()->default_value("65379:0"), "")
    ("altgr.Key107", po::value<string>()->default_value("65535:127"), "")
    ("altgr.Key108", po::value<string>()->default_value("65421:13"), "")
    ("altgr.Key109", po::value<string>()->default_value("65508:0"), "")
    ("altgr.Key110", po::value<string>()->default_value("65299:0"), "")
    ("altgr.Key111", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key112", po::value<string>()->default_value("65455:47"), "")
    ("altgr.Key113", po::value<string>()->default_value("65027:0"), "")
    ("altgr.Key114", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key115", po::value<string>()->default_value("65515:0"), "")
    ("altgr.Key116", po::value<string>()->default_value("65516:0"), "")
    ("altgr.Key117", po::value<string>()->default_value("65383:0"), "")
    ("altgr.Key118", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key119", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key120", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key121", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key122", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key123", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key124", po::value<string>()->default_value("65027:0"), "")
    ("altgr.Key125", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key126", po::value<string>()->default_value("65469:61"), "")
    ("altgr.Key127", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key128", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key129", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key130", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key131", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key132", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key133", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key134", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key135", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key136", po::value<string>()->default_value("0:0"), "")
    ("altgr.Key137", po::value<string>()->default_value("0:0"), "")

    ("capslock.Key8", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key9", po::value<string>()->default_value("65307:27"), "")
    ("capslock.Key10", po::value<string>()->default_value("49:49"), "")
    ("capslock.Key11", po::value<string>()->default_value("50:50"), "")
    ("capslock.Key12", po::value<string>()->default_value("51:51"), "")
    ("capslock.Key13", po::value<string>()->default_value("52:52"), "")
    ("capslock.Key14", po::value<string>()->default_value("53:53"), "")
    ("capslock.Key15", po::value<string>()->default_value("54:54"), "")
    ("capslock.Key16", po::value<string>()->default_value("55:55"), "")
    ("capslock.Key17", po::value<string>()->default_value("56:56"), "")
    ("capslock.Key18", po::value<string>()->default_value("57:57"), "")
    ("capslock.Key19", po::value<string>()->default_value("48:48"), "")
    ("capslock.Key20", po::value<string>()->default_value("223:223"), "")
    ("capslock.Key21", po::value<string>()->default_value("65105:180"), "")
    ("capslock.Key22", po::value<string>()->default_value("65288:8"), "")
    ("capslock.Key23", po::value<string>()->default_value("65289:9"), "")
    ("capslock.Key24", po::value<string>()->default_value("81:81"), "")
    ("capslock.Key25", po::value<string>()->default_value("87:87"), "")
    ("capslock.Key26", po::value<string>()->default_value("69:69"), "")
    ("capslock.Key27", po::value<string>()->default_value("82:82"), "")
    ("capslock.Key28", po::value<string>()->default_value("84:84"), "")
    ("capslock.Key29", po::value<string>()->default_value("90:90"), "")
    ("capslock.Key30", po::value<string>()->default_value("85:85"), "")
    ("capslock.Key31", po::value<string>()->default_value("73:73"), "")
    ("capslock.Key32", po::value<string>()->default_value("79:79"), "")
    ("capslock.Key33", po::value<string>()->default_value("80:80"), "")
    ("capslock.Key34", po::value<string>()->default_value("220:220"), "")
    ("capslock.Key35", po::value<string>()->default_value("43:43"), "")
    ("capslock.Key36", po::value<string>()->default_value("65293:13"), "")
    ("capslock.Key37", po::value<string>()->default_value("65507:0"), "")
    ("capslock.Key38", po::value<string>()->default_value("65:65"), "")
    ("capslock.Key39", po::value<string>()->default_value("83:83"), "")
    ("capslock.Key40", po::value<string>()->default_value("68:68"), "")
    ("capslock.Key41", po::value<string>()->default_value("70:70"), "")
    ("capslock.Key42", po::value<string>()->default_value("71:71"), "")
    ("capslock.Key43", po::value<string>()->default_value("72:72"), "")
    ("capslock.Key44", po::value<string>()->default_value("74:74"), "")
    ("capslock.Key45", po::value<string>()->default_value("75:75"), "")
    ("capslock.Key46", po::value<string>()->default_value("76:76"), "")
    ("capslock.Key47", po::value<string>()->default_value("214:214"), "")
    ("capslock.Key48", po::value<string>()->default_value("196:196"), "")
    ("capslock.Key49", po::value<string>()->default_value("65106:94"), "")
    ("capslock.Key50", po::value<string>()->default_value("65505:0"), "")
    ("capslock.Key51", po::value<string>()->default_value("35:35"), "")
    ("capslock.Key52", po::value<string>()->default_value("89:89"), "")
    ("capslock.Key53", po::value<string>()->default_value("88:88"), "")
    ("capslock.Key54", po::value<string>()->default_value("67:67"), "")
    ("capslock.Key55", po::value<string>()->default_value("86:86"), "")
    ("capslock.Key56", po::value<string>()->default_value("66:66"), "")
    ("capslock.Key57", po::value<string>()->default_value("78:78"), "")
    ("capslock.Key58", po::value<string>()->default_value("77:77"), "")
    ("capslock.Key59", po::value<string>()->default_value("44:44"), "")
    ("capslock.Key60", po::value<string>()->default_value("46:46"), "")
    ("capslock.Key61", po::value<string>()->default_value("45:45"), "")
    ("capslock.Key62", po::value<string>()->default_value("65506:0"), "")
    ("capslock.Key63", po::value<string>()->default_value("65450:42"), "")
    ("capslock.Key64", po::value<string>()->default_value("65513:0"), "")
    ("capslock.Key65", po::value<string>()->default_value("32:32"), "")
    ("capslock.Key66", po::value<string>()->default_value("65509:0"), "")
    ("capslock.Key67", po::value<string>()->default_value("65470:0"), "")
    ("capslock.Key68", po::value<string>()->default_value("65471:0"), "")
    ("capslock.Key69", po::value<string>()->default_value("65472:0"), "")
    ("capslock.Key70", po::value<string>()->default_value("65473:0"), "")
    ("capslock.Key71", po::value<string>()->default_value("65474:0"), "")
    ("capslock.Key72", po::value<string>()->default_value("65475:0"), "")
    ("capslock.Key73", po::value<string>()->default_value("65476:0"), "")
    ("capslock.Key74", po::value<string>()->default_value("65477:0"), "")
    ("capslock.Key75", po::value<string>()->default_value("65478:0"), "")
    ("capslock.Key76", po::value<string>()->default_value("65479:0"), "")
    ("capslock.Key77", po::value<string>()->default_value("65407:0"), "")
    ("capslock.Key78", po::value<string>()->default_value("65300:0"), "")
    ("capslock.Key79", po::value<string>()->default_value("65429:0"), "")
    ("capslock.Key80", po::value<string>()->default_value("65431:0"), "")
    ("capslock.Key81", po::value<string>()->default_value("65434:0"), "")
    ("capslock.Key82", po::value<string>()->default_value("65453:45"), "")
    ("capslock.Key83", po::value<string>()->default_value("65430:0"), "")
    ("capslock.Key84", po::value<string>()->default_value("65437:0"), "")
    ("capslock.Key85", po::value<string>()->default_value("65432:0"), "")
    ("capslock.Key86", po::value<string>()->default_value("65451:43"), "")
    ("capslock.Key87", po::value<string>()->default_value("65436:0"), "")
    ("capslock.Key88", po::value<string>()->default_value("65433:0"), "")
    ("capslock.Key89", po::value<string>()->default_value("65435:0"), "")
    ("capslock.Key90", po::value<string>()->default_value("65438:0"), "")
    ("capslock.Key91", po::value<string>()->default_value("65439:0"), "")
    ("capslock.Key92", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key93", po::value<string>()->default_value("65406:0"), "")
    ("capslock.Key94", po::value<string>()->default_value("60:60"), "")
    ("capslock.Key95", po::value<string>()->default_value("65480:0"), "")
    ("capslock.Key96", po::value<string>()->default_value("65481:0"), "")
    ("capslock.Key97", po::value<string>()->default_value("65360:0"), "")
    ("capslock.Key98", po::value<string>()->default_value("65362:0"), "")
    ("capslock.Key99", po::value<string>()->default_value("65365:0"), "")
    ("capslock.Key100", po::value<string>()->default_value("65361:0"), "")
    ("capslock.Key101", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key102", po::value<string>()->default_value("65363:0"), "")
    ("capslock.Key103", po::value<string>()->default_value("65367:0"), "")
    ("capslock.Key104", po::value<string>()->default_value("65364:0"), "")
    ("capslock.Key105", po::value<string>()->default_value("65366:0"), "")
    ("capslock.Key106", po::value<string>()->default_value("65379:0"), "")
    ("capslock.Key107", po::value<string>()->default_value("65535:127"), "")
    ("capslock.Key108", po::value<string>()->default_value("65421:13"), "")
    ("capslock.Key109", po::value<string>()->default_value("65508:0"), "")
    ("capslock.Key110", po::value<string>()->default_value("65299:0"), "")
    ("capslock.Key111", po::value<string>()->default_value("65377:0"), "")
    ("capslock.Key112", po::value<string>()->default_value("65455:47"), "")
    ("capslock.Key113", po::value<string>()->default_value("65027:0"), "")
    ("capslock.Key114", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key115", po::value<string>()->default_value("65515:0"), "")
    ("capslock.Key116", po::value<string>()->default_value("65516:0"), "")
    ("capslock.Key117", po::value<string>()->default_value("65383:0"), "")
    ("capslock.Key118", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key119", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key120", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key121", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key122", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key123", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key124", po::value<string>()->default_value("65027:0"), "")
    ("capslock.Key125", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key126", po::value<string>()->default_value("65469:61"), "")
    ("capslock.Key127", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key128", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key129", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key130", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key131", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key132", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key133", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key134", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key135", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key136", po::value<string>()->default_value("0:0"), "")
    ("capslock.Key137", po::value<string>()->default_value("0:0"), "")

    ("shiftcapslock.Key8", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key9", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key10", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key11", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key12", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key13", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key14", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key15", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key16", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key17", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key18", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key19", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key20", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key21", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key22", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key23", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key24", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key25", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key26", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key27", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key28", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key29", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key30", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key31", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key32", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key33", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key34", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key35", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key36", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key37", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key38", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key39", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key40", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key41", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key42", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key43", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key44", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key45", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key46", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key47", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key48", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key49", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key50", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key51", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key52", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key53", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key54", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key55", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key56", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key57", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key58", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key59", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key60", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key61", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key62", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key63", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key64", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key65", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key66", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key67", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key68", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key69", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key70", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key71", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key72", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key73", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key74", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key75", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key76", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key77", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key78", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key79", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key80", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key81", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key82", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key83", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key84", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key85", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key86", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key87", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key88", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key89", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key90", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key91", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key92", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key93", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key94", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key95", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key96", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key97", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key98", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key99", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key100", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key101", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key102", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key103", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key104", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key105", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key106", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key107", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key108", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key109", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key110", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key111", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key112", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key113", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key114", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key115", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key116", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key117", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key118", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key119", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key120", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key121", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key122", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key123", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key124", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key125", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key126", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key127", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key128", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key129", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key130", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key131", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key132", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key133", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key134", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key135", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key136", po::value<string>()->default_value(""), "")
    ("shiftcapslock.Key137", po::value<string>()->default_value(""), "")
    ;

    try{
        po::variables_map vm;
        po::store(po::parse_config_file(Keymap_stream, Keymap_desc), vm);
        po::notify(vm);

        int key_num;
        char buffer[256];

        struct keydef {
            struct key_info (& ki)[128];
            const char * format;
        } keydef[5] = {
            { this->keys_noshift,      "noshift.Key%d"},
            { this->keys_shift,        "shift.Key%d"},
            { this->keys_altgr,        "altgr.Key%d"},
            { this->keys_capslock,     "capslock.Key%d"},
            { this->keys_shiftcapslock,"shiftcapslock.Key%d"}
        };

        for (int kn = 0; kn < 5 ; kn++){
            for (key_num = 8; key_num < 128; key_num++){
                sprintf(buffer, keydef[kn].format, key_num);
                string key(buffer);
                string key_tmp = vm[key].as<string>();
                const char * pos = ::index(key_tmp.data(), ':');
                if (pos){
                        keydef[kn].ki[key_num].chr = atoi(pos + 1);
                }
                keydef[kn].ki[key_num].sym = atoi(key_tmp.data());
            }
        }
    } catch (exception& e){
        clog << "Exception raised " << e.what();
#warning is it really what we want ? to exit program (close session) when keymap file is malformed ?
        LOG(LOG_ERR, "failed to read keymap\n");
        _exit(1);
    };
}
