#!/bin/bash

bt () {
  esc="$(echo -e "\e")"
  sed -E '/ at /{
    s# at (.*/)?([^:]+):([0-9]+)$# at '$esc'[0;33;48m\1'$esc'[1;33;48m\2'$esc'[m:'$esc'[0;33;48;2;44;44;44m\3'$esc'[m#
  }'
}

hbt () {
  esc="$(echo -e "\e")"
  source-highlight -f esc -s cpp | \
  sed -E '/ at | '$esc'\[[0-9]+mat'$esc'\[m /{
    s#'$esc'\[[0-9]+m(..)?/'$esc'\[m#/#g;
    s#'$esc'\[[0-9]+m\.'$esc'\[m#.#g;
    s# (at|'$esc'\[[0-9]+mat'$esc'\[m) (.*/)?([^:]+):'$esc'\[m'$esc'\[[0-9]+m([0-9]+)'$esc'\[m$# at '$esc'[0;33;48m\2'$esc'[1;33;48m\3'$esc'[m:'$esc'[0;33;48;2;44;44;44m\4'$esc'[m#
  }'
}

qbt () {
  grep --color=auto -C11 ' at .\+:[0-9]\+$'
}

usage () {
  echo "$0 [-hqsef] [--help] command [-- [gdb-args...]]"
  echo ' -h,--help    Show this help message and exit.'
  echo ' -q           Quick backtrace.'
  echo ' -s           Use source-highlight.'
  echo ' -e           Catch exceptions.'
  echo ' -f           Used as filter (... | '"$0" -f').'
  echo ' -r           gdb run command arguments.'
  echo ' -l line      Breakpoint line.'
  echo ' -p file      Breakpoint file.'
}

filter=bt
nogdb=0
cmd_extra=''
cmd_run='r'
break_line=
break_file=

TEMP=`getopt -o hqsfer:l:p: --long help -n "$0" -- "$@"`
[ $? -ne 0 ] && exit 1
eval set -- "$TEMP"
while true ; do
  case "$1" in
    -h|--help) usage ; exit 0 ;;
    -q) filter=qbt ; shift ;;
    -s) filter=hbt ; shift ;;
    -e) cmd_extra='catch throw' ; shift ;;
    -f) nogdb=1 ; shift ;;
    -l) break_line="$2" ; shift 2 ;;
    -p) break_file="$2" ; shift 2 ;;
    -r) cmd_run="r ${2}" ; shift 2 ;;
    --) shift ; break ;;
    *) break ;;
  esac
done

if [ $nogdb -eq 1 ] ; then
  $filter
  exit $?
fi

[ -z "$1" ] && usage >&2 && exit 1

command="$1"
shift

if [ ! -z "$break_line" ] ; then
  [ -z "$break_file" ] && break_file="${command/*\//}.cpp"
  cmd_extra+=$(echo -e "\nb ${break_file}:$break_line\n$cmd_run\nc")
elif [ ! -z "$break_file" ] ; then
  cmd_extra+=$(echo -e "\nb ${break_file}\n$cmd_run\nc")
else
  [ ! -z "$cmd_extra" ] && cmd_extra+=$(echo)
  cmd_extra+="$cmd_run"
fi

gdb -q "$@" "$command" <<< "$cmd_extra
bt" 2>&1| $filter
