#!/bin/sh

# cppcoreguidelines-pro-type-member-init / hicpp-member-init false positive...

${CLANG_TIDY:=clang-tidy} -checks='*,
-modernize-raw-string-literal
-android-cloexec-open,
-clang-diagnostic-deprecated-declarations,
-cppcoreguidelines-pro-bounds-array-to-pointer-decay,
-cppcoreguidelines-pro-bounds-constant-array-index,
-cppcoreguidelines-pro-bounds-pointer-arithmetic,
-cppcoreguidelines-pro-type-member-init,
-cppcoreguidelines-pro-type-union-access,
-cppcoreguidelines-pro-type-vararg,
-cppcoreguidelines-special-member-functions,
-fuchsia-default-arguments,
-fuchsia-overloaded-operator,
-google-build-using-namespace,
-google-readability-namespace-comments,
-google-readability-todo,
-google-runtime-int,
-google-runtime-references,
-hicpp-braces-around-statements,
-hicpp-exception-baseclass,
-hicpp-member-init,
-hicpp-no-array-decay,
-hicpp-signed-bitwise,
-hicpp-special-member-functions,
-hicpp-use-auto,
-hicpp-use-equals-default,
-hicpp-use-equals-delete,
-hicpp-vararg,
-llvm-header-guard,
-llvm-include-order,
-misc-macro-parentheses,
-misc-unused-parameters,
-modernize-use-auto,
-readability-avoid-const-params-in-decls,
-readability-braces-around-statements,
-readability-implicit-bool-conversion,
-readability-static-accessed-through-instance,' \
-config='{CheckOptions: [{key: llvm-namespace-comment.ShortNamespaceLines, value: 10}]}' \
-header-filter='.*' \
$(find src/ -name '*.cpp' \
    -a -not -path 'src/ftests/*' \
    -a -not -path 'src/keyboard/*' \
    -a -not -path 'src/openssl_c/*' \
    -a -not -path 'src/proto/*' \
    -a -not -path 'src/sashimi/*' \
    -a -not -path 'src/system/emscripten/*' \
    -a -not -path 'src/utils/crypto/*' \
    -a -not -name app_path.cpp \
    -a -not -name log_as_logemasm.cpp) \
-- \
-std=c++17 \
-I'include' \
-I'modules/includes' \
-I'modules/ppocr/includes/mln' \
-I'modules/ppocr/src' \
-I'projects/ocr1/include' \
-I'projects/redemption_configs/include/autogen' \
-I'projects/redemption_configs/redemption_src' \
-I'src' \
-I'src/system/linux' \
-I'tests/includes/'

# highlighting
# sed "s#`pwd`/##" | colout '(^[ps][^/]+/[^:]+):([^:]+:[^:]+): (error)?(warning)?(note)?:([^[]+)(\[.*)?' c y r,o m,o c,o \#eee,o w
