#!/bin/sh

cmd="$1"
[ -z "$cmd" ] && cmd="$(dirname "$0")"/cppcheck
[ $# -ge 1 ] && shift

"$cmd" \
  --template='cppcheck [{file}:{line}]: ({severity}) [{id}] {message}' \
  --suppress=unusedFunction \
  --suppress=unusedStructMember \
  --suppress=uninitMemberVar \
  --suppress=selfInitialization \
  --suppress=noExplicitConstructor \
  --suppress=CastIntegerToAddressAtReturn \
  --suppress=obsoleteFunctionsindex \
  --suppress=unmatchedSuppression \
  --suppress=variableHidingEnum \
  --suppress=unassignedVariable \
  --suppress=noConstructor \
  --suppress=noCopyConstructor \
  "$@"
