#!/bin/sh

cd "$(dirname "$0")"/../..

exec cppcheck -v --enable=all --std=posix --std=c++11 --inline-suppr "$@" \
 `find src/capture src/core src/front src/main src/mod src/transport src/utils src/acl include/configs -name '*.?pp'`
