#!/bin/bash

d="$(dirname "$0")"

usage () {
  echo "$0 [-hcpqs] [--help] command line [-- [gdb-args...]]"
  echo ' -h,--help    Show this help message and exit.'
  echo ' -c           Show only function stack (enable by -p).'
  echo ' -p           Show previous line.'
  echo ' -q           Quick backtrace.'
  echo ' -s           Use source-highlight.'
}

opt_gtrace=''
opt_bt=''

TEMP=`getopt -o hcpqs --long help -n "$0" -- "$@"`
[ $? -ne 0 ] && exit 1
eval set -- "$TEMP"
while true ; do
  case "$1" in
    -h|--help) usage ; exit 0 ;;
    -c|-p) opt_gtrace=$1' ' ; shift ;;
    -q|-s) opt_bt=$1' ' ; shift ;;
    --) shift ; break ;;
    *) break ;;
  esac
done

[ -z "$1" -o -z "$2" ] && usage >&2 && exit 1
command="$1"
line="$2"
shift 2

[ "$1" = '--' ] && shift

"$d"/gtrace $opt_gtrace "$command" -- -ex "b $(basename "$command").cpp:$line" "$@" | "$d"/bt -f $opt_bt
