#!/bin/bash

# [-b function] [-f gdb_option] [-c] [-r exec_option] [-h] -x executable

if [ "$1" = '-h' ] || [ -z "$1" ] ; then
  echo "$0 [-c] exec"
  exit 1
fi

show_caller=0
[ "$1" = '-c' ] && show_caller=1 && shift

prev=''
(echo -e "b main\nr\ns\n"; yes '') \
| exec gdb "$@" \
|& while read l ; do
  if [ "$l" = '(gdb) The program is not being run.' ] ; then
    l=`ps | grep gdb'$'`
    read pid other <<<"$l"
    kill -s TERM $pid
    exit
  fi

  if [[ $l =~ ' at ' ]] ; then
    [ $show_caller = 1 ] && echo -e "\tl.${prev/(gdb) /}"
    echo ${l/(gdb) /}
  fi

  prev="$l"
done

exit 2
