#!/bin/bash

echo 'digraph G {'

for f in "$@" ; do
    e="${f:4}"
    #sed -nE 's/^\s*#include "([^"]+)"/'\""${e//\//\\\/}"\"' -> "\1";/p' "$f"
    sed -nE 's/^\s*#include "([^"]+)"/"\1" -> '\""${e//\//\\\/}"\"';/p' "$f"
done

echo '}'
