#!/bin/sh

if [ "$1" = '-h' ] ; then
  echo "usage: $0"' [jamdir [targets pattern-filter-cmd]]'
  echo "default is: $0 $(dirname "$0")/../.. 'libs exe' 'src/main/[_a-z]+\.cpp'"
  exit 1
fi

pattern=src/main/'[_a-z]+\.cpp'
tagerts='libs exe'
if [ ! -z "$1" ] ; then
  cd "$(dirname "$1")" || exit $?
  [ ! -z "$2" ] && targets="$2"
  [ ! -z "$3" ] && pattern="$3"
else
  cd "$(dirname "$0")"/../..
fi

bjam debug --toolset=clang-wscan \
  cxxflags='-Wno-unknown-warning-option -fsyntax-only' \
  $targets -a -j2
