#!/bin/bash

cd "`dirname "$0"`"/../..

dirproj='src/acl src/capture src/core src/client_redemption src/core src/cxx src/front src/gdi src/main src/mod src/transport src/utils'
dirtest='src/ftests tests'

function find_unused() {
    while read l ; do
        grep -oRhEm1 "^[[:space:]]*#[[:space:]]*include[[:space:]]+\".*${l//*\//}\"" "$@" > /dev/null || echo "$l"
    done
}

unused=`find $dirproj -name '*.h' -o -name '*.hpp' | find_unused $dirproj | grep -v ^src/utils/crypto/ssl_`

echo -e "Unused files in ${dirproj// /, }:

$unused

Unused files in ${dirproj// /, }, ${dirtest// /, }:
"

find_unused $dirtest <<< "$unused"
